service: notification-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 256
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  iam:
    role:
      statements:
        - ${file(iam/sendMailIAM.yml):SendMailIAM}

resources: 
  Resources:
    MailQueue: ${file(resources/MailQueue.yml):MailQueue}

functions:
  sendMail: 
    handler: src/handlers/sendMail.handler
    events: 
      - sqs: 
          arn: ${self:custom.mailQueue.arn}
          batchSize: 1

custom: 
  mailQueue: 
    name: MailQueue-${self:provider.stage}
    arn: !GetAtt MailQueue.Arn